AllCops:
  Exclude:
    - gems/**/*
    - init_templates/**/*
    - lib/measures/**/resources/*
    - lib/openstudio/extension/core/**/*
  TargetRubyVersion: 2.7.0

require: rubocop-performance
inherit_from:
    - http://s3.amazonaws.com/openstudio-resources/styles/rubocop_v4.yml

# Reduce severity of cops routinely ignored (keep enabled)
Metrics/ClassLength:
  Severity: info

Metrics/MethodLength:
  Severity: info

Metrics/AbcSize:
  Severity: info
