name: Test Measure Gems
on: push


jobs:
  test-gems-latest:
    runs-on: ubuntu-latest

    env:
      BRANCH_NAME: ${{ github.ref_name }}
      BUILD_NUMBER: ${{ github.run_number }}
      DEPLOY_PATH: ${{ github.ref_name }}/${{ github.run_number }}

    #container:  nrel/openstudio:3.10.0
    steps:
    - name: check out repository
      uses: actions/checkout@v2
    - name: Run Docker container and copy output
      shell: bash 
      run: |
        # Run the container and name it
        docker run --name test-measures --rm \
          -v ${{ github.workspace }}:/app \
          -w /app \
          nrel/openstudio:3.10.0 \
          bash -c "openstudio --version; ruby -v; openstudio gem_list; openstudio --verbose measure -r ./lib/measures"

        # Copy the static site output from container to host
        docker ps -a 
        docker cp test-measures:/app/test ./test

        ls -al ./test
    
    - name: Sync files to S3 with branch and build in path
      shell: bash 
      run: |
          echo "Deploying to s3://${{ secrets.S3_BUCKET }}/${DEPLOY_PATH}/"
          aws s3 sync ./public s3://${{ secrets.S3_BUCKET }}/$DEPLOY_PATH/ \
            --delete \
            --acl public-read \
            --cache-control "max-age=0, no-cache, no-store, must-revalidate"

    - name: Archive static site as artifact
      uses: actions/upload-artifact@v4
      with:
        name: static-html-artifact
        path: ./test


#  test-gems-develop:
#    runs-on: ubuntu-latest
#    container:  nrel/openstudio:3.10.0
#    steps:
#    - name: check out repository
#      uses: actions/checkout@v2
#    - name: environment info
#      shell: bash 
#      run: |
#          openstudio --version
#          ruby -v
#          bundle -v
#    - name: install dependencies
#      shell: bash 
#      run: |
#          gem install parallel
#          gem install rubyXL
#    - name: run workflows
#      shell: bash 
#      run: |
#          ruby run_all_generate_reports.rb 3.10.0_prep